spring.application.name=demo

spring.config.import=optional:file:.env
server.port=${PORT:8080}
# PostgreSQL Connection
# Tell Spring to look for Railway's automatic environment variables
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# Tell Hibernate to use PostgreSQL SQL syntax
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create/update your tables when the app starts
spring.jpa.hibernate.ddl-auto=update

# Optional: Show the SQL in the console so you can see what's happening
spring.jpa.show-sql=true